apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorcrud-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazorcrud-ui
  template:
    metadata:
      labels:
        app: blazorcrud-ui
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: blazorcrud-ui
          image: ghcr.io/paawanx/blazorcrud.ui:3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: GATEWAY_BASE_URL
              value: "http://blazorcrud-gateway"
