apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorcrud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazorcrud-gateway
  template:
    metadata:
      labels:
        app: blazorcrud-gateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: blazorcrud-gateway
          image: ghcr.io/paawanx/blazorcrud.gateway:3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          volumeMounts:
            - name: yarp-config-volume
              mountPath: /app/yarp
      volumes:
        - name: yarp-config-volume
          configMap:
            name: yarp-config