apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorcrud-student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazorcrud-student-api
  template:
    metadata:
      labels:
        app: blazorcrud-student-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: blazorcrud-student-api
          image: ghcr.io/paawanx/blazorcrud.student-api:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
