apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorcrud-student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazorcrud-student-api
  template:
    metadata:
      labels:
        app: blazorcrud-student-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: blazorcrud-student-api
          image: ghcr.io/paawanx/blazorcrud.student-api:2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DB_PATH
              value: /data/appStudent.db
          volumeMounts:
            - name: student-db-storage
              mountPath: /data
      volumes:
        - name: student-db-storage
          persistentVolumeClaim:
            claimName: student-db-pvc
